### ISSUE TITLE
Alert for new Java Version / Prompt to automatically Install new java version.

### ISSUE THREAD

**Issue by longhirar** [MultiMC/Launcher#3832]
### Role

The switch to Java 16 on Minecraft 1.17 & up.

### Suggestion

When installing the latest version of Minecraft 1.17 Snapshot, I realized i need to install a new java version, so I did it but later my 1.8 client for hypixel didnt launch, so I set 1.8 Java for everything and Java 16 for mc1.17, but every time I create a new instance I need to reconfigure it, because the global configs break everything because not everything support the same Java version. A cool ideia is to prompt to install the latest Java 16 when the user is creating a new 1.17 or later instance. Another cool thing of the same subject is that i have modded a modded javaw.exe, so creating java "profiles" to choose from is a great ideia, exmaple: "Heavy profile (1.16.x & below)": 6GB Ram, Java 1.8.0_221. "(Custom profile) Reshade 1.17": 5GB RAM, Custom Java installation".

### Benefit

I spent about 1 hour trying to make all my instances boot with the new Java installed, the profiles idea would make it 100% better, so we can even choose a profile when creating an instance.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by longhirar** [comment]
I am also wondering if this can be labeled as a bug, the current process for doing the Java update to 16 is so bad.

**Comment by spannerman79** [comment]
It comes down to which MC versions you create/play the most?

If they are not snapshot/pre 1.17 - then set global to be java 8 and adjust when needed
If they are all snapshot/pre 1.17 - then set global to be java 16+ and adjust when needed

You are obviously trying to swim upstream without a paddle and didn't give much though in what you could do in order to make it easier on yourself.

**Comment by longhirar** [comment]
@spannerman79 It does not depend on that because I mainly play both.

I have 5+ years of survival play with a friend that I play a lot and I play on hypixel (1.8.9) also a lot.

Currently, my global Java version can be set to 1.8 because it's the most played, but the 1.17 update is being released tomorrow, and that will change the survival world.

The profile idea is just an expansion on what is said to support multiple java versions in the last update changelog.

**Comment by Xetaxheb** [comment]
Profiles already have support for custom java versions.... The settings tab on an individual modpack install.

Not to derail too much but could you elaborate on what you mean by you have a modded javaw.exe @longhirar ?

**Comment by longhirar** [comment]
Let me elaborate:

I'm a java developer. And a curious kid.

There is an app called reshade, that lets me use shaders on any game that uses OpenGL, but it MUST patch the game .exe, since Minecraft doesn't have a .exe, I need to patch javaw.exe. Sorry if it is confusing!

The thing that is said, is that "Configuration Profiles" (or whatever name) can be created, they can contain some configurations for the game when launched, that includes Java, Ram Amount, Etc..

I think the idea is good for me, its up here for discussion if it is good for everyone or just a button to automatically update java in MultiMC.

**Comment by kb-1000** [comment]
Reshade sounds like a great way to cause instability.
About that Oracle download: a) that's a JDK, not a JRE (Oracle provides no JREs for Java 16) and b) that's Oracle JDK instead of AdoptOpenJDK which as far as I know Mojang uses.
Also, for commercial usage of Oracle JDK has to be licensed.

**Comment by ImperatorStorm** [comment]
> About that Oracle download: a) that's a JDK, not a JRE (Oracle provides no JREs for Java 16) and b) that's Oracle JDK instead of AdoptOpenJDK which as far as I know Mojang uses.

IIRC Mojang uses Microsoft-built Java, and JDKs include JREs

**Comment by Xetaxheb** [comment]
@longhirar I half misunderstood your original issue but it seems worse than the current implementation that already accomplishes what you need.... you can already fully configure any setting on a per profile basis and introducing a "presets for configures" doesn't really make sense because each modpack either works with the global settings or needs its own configuration... as for 1.17 installs defaulting to/requiring java 16 that is a separate issue that will likely get implemented as a matter of due course and shouldn't be considered part of this issue.
Also, have you seen Optifine (and shader packs)? Because besides its performance improvements, that's what passes for reshade capability in minecraft. You shouldn't need to be adding reshade to minecraft, optifine's implementation is already quite extensive.

@kb-1000 the oracle JDK's include oracle's JRE and are the only way to get oracle's version of them.  As imperatorstorm said I believe mojang is using microsofts "Microsoft Build of OpenJDK" that recently became production ready.
https://www.microsoft.com/openjdk 
https://docs.microsoft.com/en-us/java/openjdk/download

**Comment by Xetaxheb** [comment]
here's a rough mockup of what this could look like though to save a few clicks and keystrokes... it could be a managed-profile system where you edit presets in the global settings or something (or like in the mockup just inline new/overwrite/delete) and it mirrors to all profiles set to that preset (via checking on launch?) that can't then have individual settings changed without it automatically switching to custom
![image](https://user-images.githubusercontent.com/3267055/121440280-73072180-c93c-11eb-80cc-10564e3b5028.png)

**Comment by zaphod77** [comment]
more useful info. 

There's two java versions that are used.

1) 64 bit Oracle Java 8 u51, with JavaFX. this runs all minecrafts that don't require java 16.  Mojang cannot distribute later ones, due to the licensing change. Later openJDK 8s may work, but they usually don't have javafx, which most likely causes issues. it's very hard to find an OpenJDK 8 with JavaFX. Supports intel hd graphics 2000 and 3000. later java 8's do not. If you actually somehow are running on a 32 bit system it will most likely grab the 32 bit one instead. While minecraft doesn't in itself require javafx, many mods DO. Oracles 8 u51 has it.

2) 64 bit open jdk 16 built by MS 16.0.1.9.1. later ones will probably work, but that's the exact one that's grabbed.  It does NOT includes JavaFX.

Future versions of minecraft may potentially use different versions of java. but metadata is given for them that identifies the required java versions.  

It only specifies a major version, though.  I do not yet know how to auto-download the correct one, but i know it's possible to do so by reading the metadata from Mojang.

**Comment by xcfrg** [comment]
> It's very hard to find an OpenJDK 8 with javafx
Azul zulu has builds for openjdk 8 with jfx

**Comment by peterix** [comment]
None of this is relevant to anything...

MultiMc will simply use Mojang JREs.
