### ISSUE TITLE
Consider additional configuration / warning for log4j vulnerability

### ISSUE THREAD

**Issue by emclain** [MultiMC/Launcher#4350]
### Role

I play modded Minecraft

### Suggestion

Disable jndi lookups through configuration, and warn on vulnerable Java versions

### Benefit

Security

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I know you have patched the main launcher to avoid this vulnerability, but you never know what kind of crap might come in through a mod's .jar files.  Layered security measures are generally a good idea.

1. **Update configuration**: Mojang lists a number of configuration actions that can be taken for various versions of Minecraft, since the "formatMsgNoLookups" config only works in log4j >= 2.10: https://help.minecraft.net/hc/en-us/articles/4416199399693-Security-Vulnerability-in-Minecraft-Java-Edition

2. **Warn on vulnerable versions of Java**: Qualys (a security services company) mentions that newish versions of Java also default to preventing remote code execution: 
> If the server has Java runtimes later than 8u121, then it is protected against remote code execution by defaulting “com.sun.jndi.rmi.object.trustURLCodebase” and “com.sun.jndi.cosnaming.object.trustURLCodebase” to “false”(see 
https://blog.qualys.com/vulnerabilities-threat-research/2021/12/10/apache-log4j2-zero-day-exploited-in-the-wild-log4shell)

P.S. I really appreciate the swift action you've already taken on this critical vulnerability!  Thank you!

**Comment by TLATER** [comment]
Note that a lot of these mitigations might actually not work due to a second vulnerability, unfortunately, including Mojang's recommendations. See [apache's official statement](https://logging.apache.org/log4j/2.x/security.html#CVE-2021-44228) as well as [lunasec's mitigation guide (another security services company)](https://www.lunasec.io/docs/blog/log4j-zero-day-mitigation-guide/#option-2-enable-formatmsgnolookups) including their [bad advice section](https://www.lunasec.io/docs/blog/log4j-zero-day-mitigation-guide/#known-bad-advice). Qualys themselves have since updated their article to state that their previous recommendation has been discredited.

Some of the problems caused by the second CVE might not actually trigger on Minecraft, but log4j themselves think their own codepaths may trigger it, so hey.

The only real fix seems to be updating to log4j 2.16, so I think this documentation, if anything, would just lull people into a false sense of security?

**Comment by phit** [comment]
I think https://github.com/MultiMC/Launcher/issues/4349 may be one of option if anything, but then again you can still lock up any client with 2.16 as far as I can tell https://issues.apache.org/jira/browse/LOG4J2-3230.
Closing this in favor of #4349
