### ISSUE TITLE
[V0.6.14-develop-3019 on Win32][Windows 10 64] Launcher not detecting internet access after system sleep

### ISSUE THREAD

**Issue by Jahfry** [MultiMC/Launcher#4356]
### Operating System

Windows

### Description of bug

Launcher should detect internet connection coming back up similar to how it detects when down. 

### Steps to reproduce

1) Run current Dev release of MultiMC on Windows 10 64

2) Launch an instance

3) [optional] Close instance from 2

4) Keep launcher running

5) "Sleep" the Windows machine (I've been doing overnight, unknown how long is needed, probably fairly instant)

6) "Wake" machine / login

7) Launch an instance

... at this point, step 7, even after 30 minutes, MultiMC still prompts for offline username (which it never does in step 2)

Not a big deal, just filing to get it off of my brain every time it happens :)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Khaeops** [comment]
I have this problem as of public version 0.6.14, always prompts me for my offline username when launching the game from sleep/hibernation. Have to close and restart MultiMC for it to connect again.

**Comment by p-lucero** [comment]
At least for me, this appears to be a DNS issue - specifically, an inability to resolve `authserver.mojang.com`. I've grabbed [a snippet of my logs](https://gist.github.com/p-lucero/e81b806257753bbec66073e649f06c0d), and the absolute event timestamps (`2021-12-30 00:28:21-0700` and `2021-12-30 10:45:37-0700`) seem to line up with my last two wake-from-sleep occurrences.

Possible cause: on my machine, the network adapter takes a few seconds to come online after wake-from-sleep, which is likely what causes the name resolution to fail. However, this did only start happening with the most recent release (upgrading from `0.6.13` --> `0.6.14` stable releases on Win10) so there should be a corresponding code change that also caused this behavior.

(Side note: would it be acceptable to modify the MultiMC logger to output absolute timestamps on each log line, rather than timestamps relative to program start? I find the absolute timestamps much more useful for debugging :])

**Comment by ejm554** [comment]
Yeah, I'm having this trouble too, but I have (incorrectly?) attributed it to when my Windows machine loses access to its internet connection sometime while the app was running, i.e., if the internal WiFi dropped its connection. I would expect that re-establishing a WiFi connection would allow me to use "Launch" without seeing the offline prompt. I, too, can workaround the problem by restarting MultiMC. I'm seeing this problem with Version 0.6.15-develop-3227 on win 32.

![Screenshot 2022-03-08-085818](https://user-images.githubusercontent.com/26723535/157268117-ef5a4716-7bec-4a3c-a0e1-99b649809194.png)

**Comment by Joao-Victor-Liporini** [comment]
I have this same problem, I even reported it on the multimc discord but so far I haven't received any help, in my case I use windows 11 and wired internet, I don't know why multimc doesn't fix this bug
![MultiMC_KTyT0iDxs5](https://user-images.githubusercontent.com/81539403/159757177-31d8db5d-81b6-4fc1-a919-52754a9aab39.gif)
OBS: Sorry For the bad English im from brazil

**Comment by drucifer-sc** [comment]
Version 0.6.16-3431 on win32 running Windows 10 and it's still happening. I wake my computer from hibernation or sleep, and try to launch anything from a still open MultiMC, and it prompts for offline name, indicating offline. I have to manually click on the account selection, Manage Accounts, select my account and hit refresh. Only then can I launch without being prompted or having to restart MultiMC.

Suggestion: On failure to resolve, set a timer starting at say 15 seconds after the first error to resolve, and on every subsequent failure, increase the wait period by doubling the current value for the next timer, set a cap of say 1-2 or even 4 minutes. You won't make tons of requests for no reason, and wait reasonable periods of time to resolve the underlying issue (i.e. lazy/buggy nic driver) and continue at a reasonable pace. This methodology can also be applied in reverse if you're seeking to check you're still online by pinging a server or something for general tracking purposes.

**Comment by Starmania** [comment]
As a fix, why not add a button to directly refresh the current user in this window ? 
![image](https://github.com/MultiMC/Launcher/assets/52313983/a3fcd96d-6195-49f8-a3b9-b7a762a3b35f)

**Comment by phit** [comment]
This should be resolved now.
