### ISSUE TITLE
Use Qt6

### ISSUE THREAD

**Issue by Jomyy** [MultiMC/Launcher#4429]
### Role

Arm Support for the launcher (!Not the Instances!)

### Suggestion

easy native m1 builds of the launcher

### Benefit

less battery consumtion for m1 users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
ask again in a decade, we can't even use modern Qt5 on most platforms, either way MultiMC already builds fine on ARM, there's just no point as the game doesn't even support ARM

**Comment by davidebeatrici** [comment]
Please reopen this, Qt 5 is EOL.

**Comment by phit** [comment]
unlikely to ever happen for multimc 5, the qt5 versions used have already been out of support for years

**Comment by davidebeatrici** [comment]
Just for reference, I just realized PolyMC (a fork) already supports Qt 6. However, I'm going to share my work so far just in case someone else wants to step in and pick it up.

First PRs: #5655 #5656

**Comment by a17r** [comment]
### Qt5 is declared deprecated in Gentoo

At this point in time, Linux distributions are already tracking which packages are blocking Qt5 cleanup. Real Qt Company OSS support stopped back in 2020, when public availability of LTS releases started to be delayed for 1 year, stable branch repository access got closed down (with 5.15 branch repository receiving any new LTS tag one year after commercial release) and only Qt6-relevant bugs are being fixed (then backported) since then. The final release happened on 2025-05-19, which means a) we will not get it until 2026-06-19, b) any bugs discovered since last May will not be fixed and c) no bugs since 2020-12-08 that haven't also been affecting Qt6 were fixed at all.

*At least* Gentoo, Alpine and Ubuntu are entertaining Qt6 porting trackers by now, for Gentoo, Qt5 revdep cleanups are in full swing.
https://bugs.gentoo.org/show_bug.cgi?id=qt5-removal
https://gitlab.alpinelinux.org/alpine/aports/-/issues/17114
https://ubuntu-archive-team.ubuntu.com/transitions/html/qt5-removal.html

The good news is that the porting effort to Qt6 is supposed to be much smaller than from Qt4 to Qt5. Links:
https://doc.qt.io/qt-6/portingguide.html
https://www.qt.io/blog/references-and-hints-about-porting-from-qt5-to-qt6
https://www.qt.io/blog/porting-from-qt-5-to-qt-6-using-qt5compat-library

**Comment by davidebeatrici** [comment]
There is still quite some work involved...

#5655 and #5656 didn't get any attention and I just read this in the [README](https://github.com/MultiMC/Launcher/blob/4aa2b3ce6a19f9b0e662c9b35054db23d921adf9/README.md):

> If you want to contribute, talk to us on [Discord](https://discord.gg/multimc) first.
>
> While blindly submitting PRs is definitely possible, they're not necessarily going to get accepted.

I don't have a Discord account and I don't plan to create one.

**Comment by phit** [comment]
fwiw others that wanted to contribute have also been mostly ignored on discord

**Comment by a17r** [comment]
My message was just a last ping before package removal, it can't be kept in our repositories.
