### ISSUE TITLE
Flatpak packaging for security

### ISSUE THREAD

**Issue by abb128** [MultiMC/Launcher#4537]
I have searched and found [previous discussion](https://github.com/MultiMC/Launcher/issues/3183), however the thread is now locked and there didn't seem to be much reasoning behind it.

Times have changed since then, and the Log4J vulnerability affecting even vanilla unmodded Minecraft has shown that it's important to pick which software you trust with full access to your system.

I think Flatpak packaging should be reconsidered, especially in a program that executes mods and doesn't exactly require such high level of access to the system.

**Comment by phit** [comment]
no

**Comment by ryleu** [comment]
> no

why

**Comment by yllekz** [comment]
Please add a flatpak, and do not answer with just "no" as that is not professional.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/MultiMC/Launcher/issues/4537#issuecomment-2667018736

@yllekz, I'll affirm the latter statement – @phit, we are under no auspices that you do not understand how to communicate politely. Consequently, please elaborate.

**Comment by phit** [comment]
I personally do not care and am using Flatpack on my own systems, but I have no say on the development or distribution of this project. Please refer to the issue linked in OP https://github.com/MultiMC/Launcher/issues/3183 for more information from peterix.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/MultiMC/Launcher/issues/4537#issuecomment-2667032786

@phit, if you refer to https://github.com/MultiMC/Launcher/issues/3183#issuecomment-638822464, then the comment does include any rationale, presumably because previous comments in the thread indicate a previous discussion on the topic that had already come to a conclusion.

I presume that you're just the triage assignee deferring to the decision of one of the project leads, so perhaps you can improve this situation by using GitHub's new "close as duplicate" functionality to close issues like this and the one you've linked to the original source of the decision.

I understand the problems that fundamentally arise in the build toolchain when you're working to a fairly arbitrary target that is ultimately just a virtualized environment running atop what might be very different internals. However, this has not been communicated in an official capacity to the many who have requested these packages.
