### ISSUE TITLE
You are able to download and play using a Microsoft account that does not have Minecraft

### ISSUE THREAD

**Issue by aaronhowser1** [MultiMC/Launcher#4595]
### Operating System

Windows

### Description of bug

![image](https://user-images.githubusercontent.com/15698722/159352236-8e0acb91-ebfb-4176-82cf-5da3e85bf6b8.png)

I haven't tried to confirm it myself because I don't want to make an entire MS account just for this, but apparently logging into an MS account is the only part required to download and play the game, even if the MS account doesn't have Minecraft Java.

### Steps to reproduce

N/A

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
yeah that was a bug with how it handled gamepass expiration and was fixed with https://github.com/MultiMC/Launcher/commit/94fdf13f4a113bb1ffc75a4862308f12c904b2c4

just retested on latest stable just to make sure, and it will prompt you about it

![image](https://user-images.githubusercontent.com/2097483/159353386-b07a8984-4ce1-458a-8c56-9cb9e3512ead.png)
