### ISSUE TITLE
Its not possible to login into and test DevLauncher

### ISSUE THREAD

**Issue by maramowicz** [MultiMC/Launcher#4610]
### Role

I'm don't know if its a bug or feature request. If you compile DevLauncher, you usually want to test if everything works. Because Microsoft disabled Mojang login, and its not possible to login with Microsoft without MSA client ID, its impossible (for people like me without Azure) to test if everything works. 

### Suggestion

Solution I see is make exception for DevLauncher and add possibility of not logging in and run game in offline mode. And I know, its "piracy", but in internet exist "cracked" versions of MultiMC. And usually no one compile DevLauncher without need.

### Benefit

This just add possibility to test DevLauncher. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
Not gonna happen due to the mentioned piracy issues, if you already have a game account you also have a Microsoft account, with that you can simply register your own Azure app in like 5 minutes to test with.
Instructions can be found on these pages https://github.com/MultiMC/Launcher/wiki/Custom-Build and https://github.com/MultiMC/Launcher/blob/develop/notsecrets/README.md
