### ISSUE TITLE
`.deb` from website still installs 0.6.11, but latest version is 0.6.14

### ISSUE THREAD

**Issue by ZebulanStanphill** [MultiMC/Launcher#4618]
### Operating System

Linux

### Description of bug

The `.deb` installer available at https://multimc.org/#Download still installs version 0.6.11, but 0.6.14 is the latest version, and I need to use that version so I can login with my Microsoft account (since it isn't working with 0.6.11).

I tried pressing the "Update" button in the MultiMC top toolbar, but it did nothing. I tried uninstalling and reinstalling the `.deb`, but it simply installed 0.6.11 again.

### Steps to reproduce

1. On Ubuntu, download and install the `.deb` from https://multimc.org/#Download.
2. Notice that the version is the outdated 0.6.11.

### Suspected cause

I think you guys just forgot to update the `.deb`? Not really sure how those work.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the .deb downloads whatever is latest, if you already had MultiMC installed rerunning the .deb won't do anything, use the built in update if that doesn't work read the log in the MultiMC folder to fire out what is going wrong

otherwise if you don't care about losing your current install you can wipe ~/.local/share/multimc otherwise you can get the tarball from the website and extract it to ~/.local/share/multimc manually

**Comment by ZebulanStanphill** [comment]
The built-in update button didn't do anything at all when clicked, and the log files didn't even change when pressing it. I ended up uninstalling MultiMC entirely, backing up my instances (and icons) folders, wiping `~/.local/share/multimc`, reinstalling, and then copying over the instances and icons folders. That worked, so thanks for the advice.
