### ISSUE TITLE
[Suggestion] Direct mod downloads

### ISSUE THREAD

**Issue by LuciusOfLegend** [MultiMC/Launcher#4629]
### Role

I play/create modpacks for me and my friends.

### Suggestion

I would like a way to download mods directly in the launher, specifically from curseforge.

### Benefit

I think this would increase convenience.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

At first I was imagining something like what Curseforge and GDLancher have implemented, but then I thought that that wouldn't fit very well with multimc's lightweight approach.  So then I thought you could do something like add an "install mods" button to the loader mods page of modpacks.  I'm imagining that this button would open the curseforge website but whenever you downloaded a mod it would go directly into the mods folder.  In the course of coming up with this suggestion I wondered how much more convenient this would really be, but I figured I'd mention it anyways.

**Comment by Xetaxheb** [comment]
I won't comment to whether this **ought** to be implemented in multimc, but for a basic thought looking at how Mod Organizer 2 handles this for Nexusmods and nxm:// links could provide inspiration for a solution _besides (or in additon to?) implementing a copy of overwolf's browsing curseforge's repository_. 

Essentially doing the same override of handling "curseforge://" links (the "{anvil} Install" button) such as "curseforge://install?addonId=268495&fileId=3693704"
I have no idea if overwolf (app or company) would throw a fit about curseforge:// handlers being hijacked but ¯\\\_(ツ)\_/¯
All mods are already pulled by projectid and fileid anyway, right? 

This could probably be extended into installing modpacks instead of having to search the pack browser (and at the very least all curseforge:// links will require sanity checking to find out what the user is pointing at because it's uniform for seemingly everything... i don't use the curseforge app enough to know how it's handling things but modpack, resourcepack, worlds, even non-minecraft games files, all the same handler link and layout.

Before thoughts of "well multimc is a portable program" pop up, mod organizer 2 is basically too and it's never really been an issue. Just either re-associate the curseforge:// handler on launch or have a button to do so in settings. Most people are probably not moving their install much anyway.


As an aside, things like chrome may be stupid about handling nonstandard protocols and a way to fix having to okay it every time you click a curseforge link is a registry edit (although potentially out of the scope of what multimc _should_ be touching, probably not a big deal if done)

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\URLWhitelist]

"1"="curseforge://*"
```

**Comment by Xetaxheb** [comment]
What I _will_ comment on about the idea (of having a mod browser, not about the curseforge:// handling) is that while it would be kind of nice? it's mostly irrelevant. If you look at overwolf or the prior twitch client or the prior curse client for example.... it wouldn't really be all that useful compared to building packs with manual downloads or those clients. Honestly there doesn't seem to be much point in reinventing the wheel when you can just run overwolf, click all the downloads (and in-turn, automatic dependencies, which is the only really useful feature) you want, then copy the .jars into a multimc instance or export the pack.
Likewise you can move jars out, click all the update arrows, move back/export.

BUT! If the interface for _**searching**_ curseforge was improved and more capable, then it would be an infinitely useful addition imo. The website is garbage. Overwolf is not much better. 
[modpackindex](https://www.modpackindex.com/modpack/finder) exists to find packs easily, and if something that useful was made for searching mods it would be *chefs kiss*

Checklist: 

- MC version filtering (the fact you can't do this on the website without jumping through hoops...or at all when searching or relations (hello botania dependents) )
- file update/creation ranging
- download count ranging
- description and title searches
- category filters and exclusions
- the api had at times (or still has?) tools to delineate fabric/forge mods.... and they're not used often enough by authors to rely on 100%, but could have a workaround with:
- relations: dependency / dependents and searching and types filtering (re above:  most? fabric mods are dependent on fabric-api by modmuss50 and/or cloth config api by shedaniel)
- clear file communication.... lots of mods have fabric AND forge versions, so all available info and versions/downloads need to be related because I **know** there's not enough info in the api to say with certainty something is a fabric or forge mod without downloading and doing some jar digging, or having a human guess

**Comment by phit** [comment]
never going to happen with curseforge, even its packs will be removed soon when they close down their API
if some open and sane API shows up maybe in the future

**Comment by LuciusOfLegend** [comment]
It looks like they don't have an API yet, so how can they close it down?  And what do you mean "open and sane"?

**Comment by phit** [comment]
The current CurseForge API used by MultiMC and other launchers to download mods and modpacks will be shut down [any day now](https://us15.campaign-archive.com/?u=5542885c5f38ae9a4108ab154&id=a09466e80b), the new [replacement API](https://mailchi.mp/overwolf/whats-new-with-overwolf-curseforge-november3) comes with [insane terms](https://support.curseforge.com/en/support/solutions/articles/9000207405-curse-forge-3rd-party-api-terms-and-conditions#Restrictions-and-Obligations-of-Developer) no open source launcher could fulfill.

**Comment by LuciusOfLegend** [comment]
I see.  That makes sense.  Thanks for clarifying.
