### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nguyendog** [MultiMC/Launcher#4633]
Process crashed with exit code -805306369
Forge 1.8.9 for Hypixel Skyblock
Before crash it usually just...freeze

**Comment by Xetaxheb** [comment]
Please search issues and google before posting. When you do post, please give us more information (like your mod list) and upload your client log somewhere. You can also check out the multimc discord here for quick answers: https://discord.gg/multimc

Exit code 805306369 is most likely because your minecraft ran out of memory. Try increasing the maximum ram allocated in settings->java.
