### ISSUE TITLE
a common folder about resourcepacks

### ISSUE THREAD

**Issue by Chaie2019** [MultiMC/Launcher#4667]
### Role

i play minecraft with much versions

### Suggestion

i hope to add in this feature.

### Benefit

it's convient,you needn't to copy n times,and save your disk.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

a common folder about resourcepacks in different versions.
it's convient,you needn't to copy n times,and save your disk space.
thank you!

**Comment by Hi-ImKyle** [comment]
Common folder for datapacks would be nice too, they seem to be fairly version independent.

**Comment by EsperWonder** [comment]
This would be a great idea, but a shared library would need to be grouped by game version.
This also ignores resource packs intended for specific mods.

**Comment by Xetaxheb** [comment]
As a workaround on windows, you can create a central storage for them and set up symlinks (fancy shortcuts that programs "see" as folders with their contents).

First set up your stash, get all your resource packs into one spot and note the directory, like "C:\Minecraft\MyResourcePacks\", you can shift-right-click the folder "MyResourcePacks" and "Copy as Path".

To create a symlink in any given modpack: 
1. Right click the instance and open minecraft folder.
2. Delete the existing \resourcepack\ folder.
3. Shift-right-click empty background/space in the folder with nothing selected, and choose "Open PowerShell window here"
4. Run this command: 
 `cmd /c mklink /d resourcepacks "C:\Minecraft\MyResourcePacks"`
 (replacing the directory with what you setup)

If your windows is older than 10 and it opens a black command prompt instead of the new blue powershell, the command is the same, just remove "cmd /c".
You need to do this for every instance you want accessing the shared stash. You can delete the created "folder" from instances without issues, it's just a kind of fancy shortcut pointing to the actual folder.
You can do this same thing on mac and linux too but I will leave those as an exercise to the reader.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/3861
