### ISSUE TITLE
Says I don't own Minecraft when I do.

### ISSUE THREAD

**Issue by RomanOnTop** [MultiMC/Launcher#4672]
### Description of bug

I logged into my main account and tried to load forge 1.12.2 but it said I don't own Minecraft and if I would like a demo. I checked on my feather client launcher same account and i was able to play, I have Minecraft so idk why it does that.

### Steps to reproduce

I dont have any steps.
Log into an account, I guess.

### Suspected cause

Idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Dutchs** [comment]
This is probably caused by:
```4.252 D AuthFlow: "Determining game ownership."
4.252 D Getting entitlements...
4.364 W AuthRequest::onRequestError: Error 403
4.364 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/entitlements/license?requestId=GUID_HERE - server replied: Service Unavailable"
4.364 W AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"```

**Comment by rbradley0** [comment]
Adding onto this issue, I experience this bug as well. I believe it's due to the `minecraftservices.com` service being unavailable..

I launched the MultiMC application from my terminal to get some runninng output and this caught my eye before I even attempted to launch an instance of Minecraft.

```
    2.171 D Parsing Mojang response...
    2.171 D Mojang response is valid.
    2.171 D AuthFlow: "Fetching Xbox profile."
    2.171 D Getting Xbox profile...
    2.652 D AuthFlow: "Determining game ownership."
    2.652 D Getting entitlements...
    2.753 W AuthRequest::onRequestError: Error 403
    2.753 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/entitlements/license?requestId=caae7666-0d97-43fa-80c2-71141c93feb0 - server replied: Service Unavailable"
    2.753 W AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"
    2.753 D Parsing Minecraft entitlements...
```

So I would assume that the Entitlements requester is bugged in one way or another during the startup of MultiMC, it is possible to fix this but  it requires refreshing the account you have  in MultiMC a few times. Your Mileage May Vary

**Comment by pizzaandcheese** [comment]
The issue fixed itself for me, went to start it from the terminal and saw it authenticate properly.
