### ISSUE TITLE
CurseForge modpacks not showing up

### ISSUE THREAD

**Issue by dcityman** [MultiMC/Launcher#4740]
When trying to install curseforge modpacks via the button in app, the packs don't show up

**Comment by NovaLynxie** [comment]
Noticing this too, though I suspect its something to do with Curseforge since I can't install any modpacks from there at all.
Am assuming you are seeing this when you get this when trying to search for any packs?
![image](https://user-images.githubusercontent.com/21307676/171059446-24ac6fb5-e1a6-49c1-a5a5-fddfeab589be.png)

**Comment by dcityman** [comment]
yes, that is what I see

**Comment by NovaLynxie** [comment]
Found out why after some digging, see here: https://github.com/MultiMC/Launcher/issues/4735#issuecomment-1140786518

**Comment by dcityman** [comment]
thanks

**Comment by Liflyyy** [comment]
ripppppp
hope a fix comes soon
just got back into mc i think
