### ISSUE TITLE
Can't add new minecraft 1.19 instance yet.

### ISSUE THREAD

**Issue by juliocoliveira** [MultiMC/Launcher#4755]
### Operating System

Windows

### Description of bug

Minecraft 1.19 was just released but i can't add a new instance for that version, 1.18.2 is the latest not 1.19.
![image](https://user-images.githubusercontent.com/6606725/172416628-128c30d9-b70f-4956-9676-c4628ff1ac21.png)
![image](https://user-images.githubusercontent.com/6606725/172416499-d7346a8f-d5f9-417d-ba49-45d09b0efe19.png)

### Steps to reproduce

Add a new instance

### Suspected cause

Maybe some outdated files i don't know.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by OpenBagTwo** [comment]
Since I'm just as impatient, I figured I tried:

1. Creating a new Minecraft 1.19-rc2 instance (vanilla)
1. Going into the instance folder `mmc-pack.json` and replacing "version" with "1.19"
1. Downloading Minecraft 1.19 via the official launcher (I'm on Debian-based Linux)
1. Copying the `.minecraft` folder to inside the instance folder
1. Launching the instance through the MultiMC launcher

This results in:

```
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraft/1.19.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/1.19.json
```

That is all to say, this doesn't seem to be a matter of us waiting on Mojang to push a file but rather that MultiMC needs to push the new JSON to their servers.

Anyway--**thank you, MultiMC team** for all your hard work. Y'all are absolutely awesome, and I hope issue comments like this aren't too big of an annoyance.

**Comment by mschmidt98** [comment]
There seems to have been some activity [in the meta-upstream repo](https://github.com/MultiMC/meta-upstream/commit/39de71781690094025b093154a197222520a9d0a#diff-87fc26a0eab7cb9fda443563debf785f67ea6dce29de3b32be974a22afc899c2). From my uneducated pov it seems they are working on getting the server files up.

But I just can agree to @OpenBagTwo  - Thank you for always being so quick about us naggers ❤️

**Comment by Pachin0** [comment]
Not to be desperate ( maybe a little ) but when can this be fixed. I suppose it is a quick fix, right?

**Comment by Pachin0** [comment]
It has been resolved.

**Comment by juliocoliveira** [comment]
Thanks!
