### ISSUE TITLE
Support for Bedrock version only for windows

### ISSUE THREAD

**Issue by issac4892** [MultiMC/Launcher#4765]
### Role

I manage versions with multimc

### Suggestion

Make minecraft bedrock version work with multimc

### Benefit

I won't need to use multimc and minecraft launcher together

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Microsoft announced that they will sell Minecraft: Java Edition and Minecraft Bedrock for PC together, and it happed. However, multimc does not support bedrock edition so I want MultiMC to support bedrock edition so I won't need to use multimc when i play java, and minecraft launcher when i play windows edition.

**Comment by peterix** [comment]
No. I will not do this.

**Comment by sludgepudge** [comment]
Perhaps maybe some basic reason as to why you won't? Even if it's cos you just don't want to. Rather than just being so blunt...

**Comment by cooleybyte** [comment]
wow. no wonder people dont use multimc. the owners a douche

**Comment by Forkk** [comment]
Let's try and keep things productive on the issue tracker, we don't need comments like that.

As for this feature, MultiMC is very much focused on Java edition and always has been, so this is out of scope.

**Comment by ytggobs** [comment]
Maybe if you can add an instance with a path to the Minecraft Bedrock executable maybe like:
![Concept by me](https://github.com/MultiMC/Launcher/assets/62442697/5d08aa80-eded-47c7-a2a2-1dea627ca74d)

**Comment by FlushDesert22** [comment]
> Perhaps maybe some basic reason as to why you won't? Even if it's cos you just don't want to. Rather than just being so blunt...

Yeah, people don't like giving explanations nowadays. I would ask why but I wouldn't get an answer.

**Comment by FeedTheChunk** [comment]
[I'm not  speaking for the Devs here, this is solely my opinion] The Devs have a project scope which is for a cross platform Java Minecraft launcher.  Bedrock is neither cross platform nor java.  If fact it is strictly a Windows Application.  There's plenty of other things that I could point out but it all boils down to project scope.  Adding Bedrock is simply out of the project scope. Shaming them isn't going to change their minds.

**Comment by thowoee** [comment]
Having a Bedrock version selection or way to play the game would be excellent addition to the launcher, since it already has FTB, ATLauncher and Technic support.

I do understand if the developer with the comment earlier has a deep hate for the non Java version of the game, since Micro$oft.
But it would be useful for many people, personally I see this as all in one launcher, I don't trust or like Overwolf (The current FTB Launcher), so I use this, so it would make sense to also have a Bedrock support, exploring older versions (if possible) and playing the game. 

Maybe the authorization process is not easily available for the 3rd party launcher, but the launcher already has Micro$oft account login system, but I don't know enough how this stuff works.

**Comment by shaijyy** [comment]
It will be cool yeah I guess
