### ISSUE TITLE
Typo in launch log: "Minecraft ... requires the use of Java 17"

### ISSUE THREAD

**Issue by SteelRodent** [MultiMC/Launcher#4877]
### Operating System

Windows

### Description of bug

Attempting to get my custom 1.18 MC up and running and it failed because I'm on the latest version of Java. The failed to launch log tells me

`Minecraft 1.18 Pre Release 2 and above require the use of Java 17`

Since Java is currently on version 8 I assume this error is supposed to say Java 7. I'm aware the JDK is version 17 and 18, but if "normal" people are going to download the JRE they need to look for Java 7 and the error should reflect that to avoid confusion. 

### Steps to reproduce

- Install Java 8 
- setup instance in MultiMC with MC 1.17 or later
- launch and observe console log

EDIT: So after some googling I discovered that Java 17 appears to be an actual thing, but there does not appear to be any way for end users to download the JRE (at least not from Oracle). Which only makes that error message more useless.

EDIT 2: to clarify, when you go to Java.com it wants you to download Java 8. Requires some searching to get to the Java 17 SDK, but it's not obvious that is what you want (I for one didn't know they stopped making the JRE). Also now that I've figured it out I'm sorry for opening this ticket, but can't seem to delete it. MC is the only Java program I got that whines about the Java version, and I play it so rarely I usually don't have to deal with it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by coolpringles** [comment]
You can run the game fine with the JDK, just install it the same as you would anything else and MultiMC should pick it up like any other java version you have installed.
https://download.oracle.com/java/17/archive/jdk-17.0.4_windows-x64_bin.msi
https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#windows

**Comment by RedHornsAndEyes** [comment]
If you are having this issue and definitely have a more recent version of Java try this
 settings > Java > auto detect > choose one that will work
![image](https://github.com/MultiMC/Launcher/assets/93504911/0e467c16-0a0d-4f77-9eb0-2bdb4668c8f9)
![image](https://github.com/MultiMC/Launcher/assets/93504911/19426ae9-7695-436a-8ccb-9a407af2700a)
![image](https://github.com/MultiMC/Launcher/assets/93504911/d2bbe665-72ee-413f-9109-b20e03e2007e)
![image](https://github.com/MultiMC/Launcher/assets/93504911/6ad5a123-4a7e-4a4e-a9c9-53a2a9ac1327)
this gave me a bit of trouble just because I didn't think of it. On the plus side now I have Java 20 installed.
