### ISSUE TITLE
Erros de login, conta deslogando e com erro ao login

### ISSUE THREAD

**Issue by Joseplay1012** [MultiMC/Launcher#5137]
### Description of bug

Toda vez em que logo na conta ele da erro, quando eu fecho o progama e ele pede para logar novamente e da erro ao logar, siceramente estou migrando para outro laucher que nao fique dando essses erros ate porque e chato ter que toda hora esperar a vontade do launcher para jogar minecraft, o launcher so loga na conta quando quer, isso e chato demas enquanto nao resolver esse erro nao volto mas para o launcher. voçês devem ta falando, você saindo nao vai mudar nada, claro que nao mas se o erro continuar nao sei se e so eu que vou estar saindo do laucher nao! entao eu pesso que arrumen isso pois nao e legal toda hora ter que ficar logando no launcher, e esperar a boa vontade do launcher logar na conta. esse erro esta aconteçendo com contas Microsoft! algums estao sem o poblema mas outros estao tendo o pobrema

### Steps to reproduce

Sessão de Gravação: ‎26/‎04/‎2023 17:13:29 - 17:13:56

Passos Gravados: 11, Passos Ausentes: 0, Outros Erros: 0

Sistema Operacional: 19041.1.amd64fre.vb_release.191206-1406 10.0.0.0.2.100

### Suspected cause

nova versao!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Joao-Victor-Liporini** [comment]
### **Operating System** 
Windows 10 OS 64Bits

### **Description of bug**
Every time I log into the account it gives error, when I close the program and it asks to login again and gives error when logging in, I am migrating to another laucher that is not giving these errors because it is annoying to have to wait all the time the will of the launcher to play minecraft, the launcher only log into the account when you want, this is annoying too while I do not solve this error I will not return to the launcher. you must be saying, you leaving will not change anything, of course not but if the error continues I do not know if I am the only one who will be leaving the laucher no! so I ask you to fix it because it is not cool to have to be logging into the launcher all the time, and wait for the goodwill of the launcher to log into the account. this error is happening with Microsoft accounts! some are without the problem but others are having the problem

### **Steps to reproduce**
Close the launcher and it will ask you to log in again.

### **Suspected cause**
New Version!

### **This issue is unique**

- [x]  I have searched the issue tracker and did not find an issue describing my bug.

### **Adding an English translation for those who are not fluent**

Next time use a translator (like [DeepL](https://www.deepl.com/pt-BR/translator) or [Google Translator](https://translate.google.com/)) because not everyone is fluent in Portuguese Brasilian

Da próxima vez, use um tradutor (como [DeepL](https://www.deepl.com/pt-BR/translator) ou [Google Translator](https://translate.google.com/)) porque nem todo mundo é fluente em português do Brasil

**Comment by Joseplay1012** [comment]
Sorry I thought you had staff that spoke Brazilian, so I'll attach a video
file so you can try to understand!

Em seg., 1 de mai. de 2023 21:33, João Victor ***@***.***>
escreveu:

**Comment by phit** [comment]
we have no control over the login flow, if you have an actual issue outside of microsoft blocking certain api calls please provide a reproduction and logs
