### ISSUE TITLE
I Hope Can Provide MultiMC For Windows Installer.

### ISSUE THREAD

**Issue by AkarinLiu** [MultiMC/Launcher#5175]
### Role

I want to install to the my Computer, Not Installation free.

### Suggestion

Provide Windows Installer Edition & Portable Edition.

### Benefit

Windows Installer makes it easier to install software and does not need to configure the registry if you want to run it on a USB stick。

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by mk-pmb** [comment]
There is another (inofficial) project that seems to be trying to provide this: https://github.com/modpotato/MultiMC-Installer
Their downloads page is here: [releases/tag/Release](https://github.com/modpotato/MultiMC-Installer/releases/tag/Release)


> I want to install to the my Computer,

Just to make sure we're talking about the same thing, afaik to "install" MultiMC on Windows means

1. Download the Windows ZIP file from https://multimc.org/#Download
2. Open ZIP file properties and at bottom of first properties page, uncheck the checkbox that says something like "This file is dangerous because it's downloaded fron the internet." 
    * Actually this is probably the hardest step because it's not intuitive, it's easy to forget, and forgetfulness taints all of the unpacked files.
    * Also this step seems to be missing from the install instructions in the link above.
3. Right-click the ZIP, click "extract".
4. Move the resulting folder to where you want it. (Discerning the ZIP from the extracted folder might confuse some users, depending on file manager settings.)
5. Delete the ZIP. (Same confusion.)
6. Drag (with secondary mouse button) MultiMC.exe to Desktop, select "Create shortcut".


> Not Installation free.

What do you mean by that? I guess the installer should do most of the steps I just described?
I'd hope the project linked above can do that.

[Chocolatey](https://en.wikipedia.org/wiki/Chocolatey) can also do it: `choco install multimc`


> does not need to configure the registry if you want to run it on a USB stick,

I don't think we're using the registry currently. When you extract the ZIP to a USB thumb drive, it should work as is.

**Comment by AkarinLiu** [comment]
But MultiMC Installer Latest is at Feb 28, 2022.
![图片](https://github.com/MultiMC/Launcher/assets/58081491/f8ce05e3-eec9-4312-bdbe-6e4a6f73b7c3)

**Comment by mk-pmb** [comment]
Yeah. Is that a problem? The install process hasn't changed recently, so an old installer might still be able to download the latest version of MultiMC. I don't know if their installer is smart enough to do that, but it might be worth a try.

**Comment by AkarinLiu** [comment]
I try it, I think very good! Thanks care, @mk-pmb!
