### ISSUE TITLE
Add support for offline accounts (without microsoft/mojang login)

### ISSUE THREAD

**Issue by ac3ss0r** [MultiMC/Launcher#5215]
### Role

I play modded minecraft.

### Suggestion

Add offline auth (without the need to add accounts)

### Benefit

More people can use the launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Obviously most part of the community doesn't own licensed accounts and plays using offline (pirated) game. Mojang doesn't even care about that or take any actions either. All popular launchers such as tlauncher, tl-pro, mlauncher have this. Not implementing offline in multimc is a huge disadvantage which makes the launcher unusable for most people. It would be great if you implemented the offline mode

**Comment by FeedTheChunk** [comment]
Just because Mojang "doesn't even care" doesn't make it legal.  Allowing and ignoring the fact that users are using a pirated copy of the game makes the author(s) of the launcher complicit in your crimes.  You're asking MultiMC authors to brake the law so that you can break the law.  That takes a set of big balls.

**Comment by sp7n0** [comment]
nuh uh
