### ISSUE TITLE
log in problem

### ISSUE THREAD

**Issue by szymongame087** [MultiMC/Launcher#5291]
### Description of bug

whatever i do or any account i use i just can't log in because xbox 
account appears
### Steps to reproduce

I have an account on two websites

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by blippyp** [comment]
I'm also trying to get MultiMC to work for my kid since the Microsoft Launcher is a complete buggy mess that won't install properly. Whenever I try to log in however, I get the same problem regarding an xbox authentication issue.  This is on a fresh install of Windows 7 with Microsoft Visual C++ 2015 Redistributable installed as well.

**Comment by phit** [comment]
There's not enough information here to really help either of you, if you need help going through your logs to find the actual issue ask in the [MultiMC Discord](https://discord.gg/multimc). For Windows 7 specifically make sure your root certificates are updated.
