### ISSUE TITLE
Add .mcmeta mod support

### ISSUE THREAD

**Issue by Moltresrider** [MultiMC/Launcher#5403]
### Operating System

Windows

### Description of bug

the current version of MultiMC does not have support for mods that are packed into a .mcmeta file

I downloaded a texture pack and inside the zip contains a .mcmeta file

However, when I try to go to "add mod", that .mcmeta file does not appear as a valid file to choose from

It seems that MultiMC onlt supports .litemod but NOT .mcmeta

### Steps to reproduce

Download this mod: https://www.curseforge.com/minecraft/texture-packs/clear-water-and-lava/files/4312412
extract to a folder
Put that folder in the same directory as MultiMC
Go to instance settings
click "add mod"
browse to mod folder
the .mcmeta file cannot be selected.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
You should be adding this to the resource pack not the mods section.  The file you referenced is a resource pack and not a mod.  Or am I misunderstanding you?

Adding it to the resource pack section worked fine for me:

![image](https://github.com/MultiMC/Launcher/assets/35508630/475520a8-f773-4635-98b6-84e71c0b12c7)


And BTW: You shouldn't be extracting the resource file.  You should be adding the zip file.

**Comment by Primitive-Human** [comment]
Mods and resource packs contain .mcmeta files that contain information about the archive files that they're in. Like the label on a piece of clothing.

So when you extract that .mcmeta file out of its archive and try to import that into MultiMC, you're basically just giving someone the ripped-off label of the t-shirt you got rather than the whole t-shirt. 

Do you understand how useless it is what you're suggesting?
