### ISSUE TITLE
Minecraft crushing on versions above 1.13 (Process exited with exit code -1 (0xffffffffffffffff) )

### ISSUE THREAD

**Issue by CatZ1p** [MultiMC/Launcher#5457]
Operating System
Windows

Description of bug
I tried to reinstall multimc, launch clear versions but nothig works and also swaped java versions

P.S. launching offline also cant help Nothing can help. 
[2024-07-03-3.log.gz](https://github.com/user-attachments/files/16089426/2024-07-03-3.log.gz)
[latest.log](https://github.com/user-attachments/files/16089427/latest.log)

**Comment by phit** [comment]
update multimc

**Comment by TheGoomba98** [comment]
> update multimc

Is that supposed to be a solution? I've updated MultiMC and I'm also getting this exact error.

**Comment by phit** [comment]
please post a new full log that includes the multimc metadata

**Comment by TheGoomba98** [comment]
MultiMC version: 0.7.0-3863


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.40]

textures.minecraft.net resolves to:
    [13.107.253.40]

api.mojang.com resolves to:
    [13.107.246.40]


Minecraft folder is:
C:/Users/Kyle/Downloads/MultiMC/instances/1.21/.minecraft


Java path is:
C:/Program Files/Eclipse Adoptium/jre-21.0.3.9-hotspot/bin/javaw.exe


Checking Java version...
Java is version 21.0.3, using 64-bit architecture, from Eclipse Adoptium.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Kyle/Downloads/MultiMC/instances/1.21/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-arm64.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-x86.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  C:/Users/Kyle/Downloads/MultiMC/libraries/com/mojang/minecraft/1.21/minecraft-1.21-client.jar

Native libraries:

Params:
  --username Goomba98 --version 1.21 --gameDir C:/Users/Kyle/Downloads/MultiMC/instances/1.21/.minecraft --assetsDir C:/Users/Kyle/Downloads/MultiMC/assets --assetIndex 17 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 35752


Using onesix launcher.

Failed to start Minecraft:
java.lang.NoClassDefFoundError: Could not initialize class axw
	at yk.<clinit>(SourceFile:34)
	at wz.c(SourceFile:229)
	at en.<clinit>(SourceFile:24)
	at ab.<clinit>(SourceFile:240)
	at ac.<init>(SourceFile:36)
	at o.<init>(SourceFile:35)
	at o.a(SourceFile:226)
	at net.minecraft.client.main.Main.main(SourceFile:207)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/joml/Matrix4f [in thread "main"]
	at axw.<clinit>(SourceFile:100)
	at azk$b.<init>(SourceFile:31)
	at azk$a.<init>(SourceFile:55)
	at azk.a(SourceFile:79)
	at azk.a(SourceFile:73)
	at gvq$c.<clinit>(SourceFile:139)
	at gvq.<clinit>(SourceFile:40)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	... 6 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 04 Jul 2024 08:48:31 -0400
MultiMC: Log upload failed!
Clipboard copy at: 04 Jul 2024 08:48:37 -0400

(Yes, I tried to upload the log to paste.ee too, and that also failed!)

**Comment by CatZ1p** [comment]
> update multimc

I haadd alreadyupdated multimc and also tried to reinstall it, nothing could help

**Comment by phit** [comment]
try deleting `C:/Users/Kyle/Downloads/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar`, otherwise something like your antivirus may be messing with the game libraries

**Comment by TheGoomba98** [comment]
Surprisingly, deleting that .jar file worked. What's up with that?

**Comment by phit** [comment]
whats your antivirus? if you both use the same one it could have been caused by a false positive

**Comment by CatZ1p** [comment]
> whats your antivirus? if you both use the same one it could have been caused by a false positive

I use malwerbytes. And what should I do? I dont have "joml" folder

**Comment by phit** [comment]
then post your log

**Comment by CatZ1p** [comment]
MultiMC version: 0.7.0-3863


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.45]

textures.minecraft.net resolves to:
    [13.107.246.45]

api.mojang.com resolves to:
    [13.107.246.45]


Minecraft folder is:
C:/MultiMC/instances/1.15.2/.minecraft


Java path is:
C:/Program Files/Java/jre-1.8/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_411, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/MultiMC/instances/1.15.2/natives

Traits:
traits FirstThreadOnMacOS

Using system OpenAL.
Using system GLFW.

Libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/MultiMC/libraries/com/mojang/minecraft/1.15.2/minecraft-1.15.2-client.jar

Native libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username cuprizen --version 1.15.2 --gameDir C:/MultiMC/instances/1.15.2/.minecraft --assetsDir C:/MultiMC/assets --assetIndex 1.15 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx8064m, -Duser.language=en]


Minecraft process ID: 15024


Using onesix launcher.

[19:09:47] [Render thread/INFO]: Setting user: cuprizen
[19:09:50] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[19:09:50] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[19:09:50] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/4/24 7:09 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dbr.<init>(SourceFile:157)
	at dbn.<init>(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: glfw.dll
	at cxm.<clinit>(SourceFile:38)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: glfw.dll
	at org.lwjgl.system.Library.loadNative(Library.java:299)
	at org.lwjgl.system.Library.loadNative(Library.java:205)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(Unknown Source)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(Unknown Source)
	at java.lang.ClassValue.getFromHashMap(Unknown Source)
	at java.lang.ClassValue.getFromBackup(Unknown Source)
	at java.lang.ClassValue.get(Unknown Source)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(Unknown Source)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(Unknown Source)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(Unknown Source)
	at cxm.<clinit>(SourceFile:35)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dbr.<init>(SourceFile:157)
	at dbn.<init>(SourceFile:394)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_411, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 784214336 bytes (747 MB) / 1223688192 bytes (1167 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 6
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8064m
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\MultiMC\instances\1.15.2\.minecraft\crash-reports\crash-2024-07-04_19.09.50-client.txt
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 04 Jul 2024 19:09:55 +0300
MultiMC: Log upload triggered at: 04 Jul 2024 19:10:11 +0300
MultiMC: Log upload failed!
Clipboard copy at: 04 Jul 2024 19:10:16 +0300

I also cant upload log. It says that host.api.ee not found

**Comment by phit** [comment]
turn off system openal and glfw, its off by default

**Comment by CatZ1p** [comment]
> turn off system openal and glfw, its off by default

tysm

**Comment by Husyay** [comment]
im having this problem too, ive deleted the jar file and such and still no luck
