### ISSUE TITLE
Proxy Issues!

### ISSUE THREAD

**Issue by BlitzenZizi** [MultiMC/Launcher#546]
So, I have looked around on here for some help on this particular issue, however, the only one I found was to turn off Proxy in settings on MultiMC. Which, still did not work. It gives me this error:
Authentication operation failed due to a network error: Proxy connection refused (99)

I am using a windows 8 computer, and the latest version of MultiMC.
I do have a paid minecraft account.
I do NOT have Minecraft.net's minecraft application installed. (please let me know if I NEED that, otherwise I won;t download it.)
I am using mods. 
I also get straight xs across the bottom which tells me if it is connected to the web, skins, account, etc.
This problem has just recently arisen, and I cannot seem to find the cause of this issue. assistance is greatly appreciated.

**Comment by BrokenHalo** [comment]
Hello,

I am experiencing the same issue as BlitzenZizi. Upon trying to login I receive the error: Authentication operation failed due to a network error: Proxy connection refused (99).

OS: Windows 7

~ I have added MultiMC to my firewall's 'allowed' list and tried just turning it off.
~ I have re-installed MultiMC
~ I have looked for any mysterious cfg files in the MultiMC folder. None found.
~ I can open and view the following link that you provided for Blitzen Zizi:    http://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.json

Have I forgotten anything? Might you have any other ideas as to what could be causing the issue?

Thank you,

BrokenHalo
